### ISSUE TITLE
look of "hidden" Mystery screen function pieces

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#1]
From https://github.com/phetsims/function-builder/issues/103#issue-209883669:

Colors for numeric Mystery functions are randomly chosen from color sets. The icons for pattern functions look good on specific background colors, and we don't want to use those colors in mystery mode because it would give away the function. Perhaps make all functions gray in mystery mode, then reveal icon+backgroundColor when revealing identity. @ariel-phet suggested using colored question marks if we use gray mystery functions.

**Comment by pixelzoom** [comment]
Here's my first pass:
http://www.colorado.edu/physics/phet/dev/html/function-basics/1.0.0-dev.1/function-basics_en.html

When hidden, the functions have a white background, and a colored question mark.  E.g.:

![screenshot_211](https://cloud.githubusercontent.com/assets/3046552/24985232/2ac4ead6-1fb0-11e7-8065-adaac2cd8da0.png)

The question mark color is currently chosen randomly from this set of colors, which is easy to change:

```js
QUESTION_MARK_COLORS: [ 'red', 'blue', 'green', 'orange', 'magenta' ]
```

The colors are randomly shuffle, no color is repeated, and no color ever appears twice in a row.  It is possible (though unlikely) for the same color to appear twice in 3-function challenges (for the 1st and 3rd function).

@amanda-phet @ariel-phet Feedback?

**Comment by ariel-phet** [comment]
@pixelzoom overall I think it looks good. I am curious to see the question marks a bit larger/thicker stroke (I think they could be a bit heavier), but otherwise looks great.

**Comment by pixelzoom** [comment]
FYI... If we make any changes to the questions mark, they would currently apply to Function Builder also.

**Comment by pixelzoom** [comment]
4/13/17 design meeting:

- [x] @pixelzoom don't allow the same color to be used for more than 1 function in a challenge
- [x] @amanda-phet test colors for color blindness
- [x] @amanda-phet specify more/different colors if desired

**Comment by pixelzoom** [comment]
I need to change the home-screen icons for Mystery in both Function Builder and Basics, use `weight: 'bold'` question mark.

**Comment by pixelzoom** [comment]
The questions marker were made larger and bold in https://github.com/phetsims/function-builder/commit/440ccd20f72e9044c4383fcde3ae187baf399bf3.

**Comment by pixelzoom** [comment]
Here's a new dev version that prevents duplicate colors in challenges, or the same color in consecutive 1-function challenges.  @amanda-phet please use this for colorblind testing.  Let me know if you want to modify the set of colors.

http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.2/function-builder-basics_en.html

**Comment by amanda-phet** [comment]
I didn't notice any issues when playing the mystery screen on different color-blind filters, so I would like to keep all of the current colors. The only one that wasn't perfect was blue vs. green in monochrome, but it doesn't seem like a case that needs to dictate a new color scheme.

**Comment by pixelzoom** [comment]
Reopening. 

@amanda-phet Funny you should mention 'blue'.  It's currently 'rgb(0,0,255)', which is sort of a darker blue, which I was thinking we might want to brighten up a bit.  Do you want to try a brighter blue, like 'rgb(0,170,255)' ?  Comparison below.

Dark blue:

![screenshot_01](https://cloud.githubusercontent.com/assets/3046552/25071537/a1cc3516-2277-11e7-83a8-795f01cbe77f.png)


Bright blue:

![screenshot_327](https://cloud.githubusercontent.com/assets/3046552/25071538/a70c3922-2277-11e7-9779-6854b5aacb1c.png)

**Comment by amanda-phet** [comment]
I like that light blue a lot! Just did a quick check for colorblindness and it looks good.

**Comment by pixelzoom** [comment]
Great, changed to light blue.  Closing.
