### ISSUE TITLE
what to do about pattern functions A, B, C ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#10]
In Function Builder, the "Patterns" screen has 3 mystery functions:

![screenshot_199](https://cloud.githubusercontent.com/assets/3046552/24813883/f3e39c0a-1b8c-11e7-8006-daa03a3c44f8.png)

For the game in Function Basics, do you want to (a) omit these functions, or (b) create icons for these functions that depict what they do?  (a) would certainly be easier, and would leave us with 9 pattern functions.

@amanda-phet @ariel-phet your opinion?

**Comment by amanda-phet** [comment]
I think these three functions should not be a part of the mystery screen (it seems odd to me to reveal a mystery function and have it be.. a mystery).

**Comment by pixelzoom** [comment]
Agreed, closing.
