### ISSUE TITLE
specify the challenge pools

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#11]
In https://github.com/phetsims/function-basics/issues/7, @amanda-phet decided that challenges will be specified similar to Function Basics.  Rather than programmatically generate random combinations of functions, we will have pools of pre-defined combinations that we will select from.  And 1 specific challenge in each pool with be consistently selected on startup and Reset All, so that teachers have a known starting point.

@amanda-phet please specify:

• pool of 1-function challenges
• pool of 2-function challenges
• pool of 3-function challenges
• For each pool, identify which challenge will be presented on startup and Reset All.

**Comment by amanda-phet** [comment]
Working on these in a google doc found [here](https://docs.google.com/spreadsheets/d/1_ndx3YmLA2H_w0iFouS6rur3EmDebyjPIf_OTmKy13M/edit#gid=0)

**Comment by amanda-phet** [comment]
Challenges have been generated.. please let me know if anything in the doc needs clarification.

**Comment by pixelzoom** [comment]
Specification is implemented in:
http://www.colorado.edu/physics/phet/dev/html/function-basics/1.0.0-dev.1/function-basics_en.html

You may also want to compare the specification with the code. See [MysteryChallenges.js](https://github.com/phetsims/function-basics/blob/master/js/mystery/model/MysteryChallenges.js).

@amanda-phet please verify.

**Comment by pixelzoom** [comment]
Forgot to mention... If you run with `?showAnswers&playAll`, then the sim will cycle through challenges in the same order that you specified in the doc.

**Comment by pixelzoom** [comment]
Latest dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.2/function-builder-basics_en.html

**Comment by pixelzoom** [comment]
@amanda-phet Are you sure you want the initial 1-function challenge to be Erase?  When I've been demo'ing the sim, it's been a little to surprising to me when I see nothing on the output cards.  I'm wondering if teachers/students might think the sim is broken.

**Comment by amanda-phet** [comment]
After playing with it I was thinking the same thing. I'll plan to change the initial function to something else.

**Comment by amanda-phet** [comment]
Can you change the initial 1-function challenge to RGB-invert? 

Can you also ADD shrink+shrink to the 2-function pool? 

The other challenges look good to me!

**Comment by pixelzoom** [comment]
@amanda-phet  Yes, I can make those changes.  But the [Google doc](https://docs.google.com/spreadsheets/d/1_ndx3YmLA2H_w0iFouS6rur3EmDebyjPIf_OTmKy13M/edit#gid=0) needs to be changed first, and I don't have edit permission.  Can you please give me edit permission?

Once I have edit permission on the Google doc, do you mind if I remove the "Key" and simply fill in the function names?  That will make it much easier for @phet-steele during testing.

**Comment by pixelzoom** [comment]
I've made the change requests in the code.  I still need to update the Google doc.  Then this issue can be closed.

**Comment by amanda-phet** [comment]
Please feel free to replace the key with the function names. (The key made it easier to fill in when I was developing the challenge combinations)

**Comment by pixelzoom** [comment]
I updated the [Google doc](https://docs.google.com/spreadsheets/d/1_ndx3YmLA2H_w0iFouS6rur3EmDebyjPIf_OTmKy13M/edit#gid=0) and put a link to it in the source code.

Closing.
