### ISSUE TITLE
verify credits for 1.0.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#14]
The credits are currently the same as Function Builder:

```js
    credits: {
      leadDesign: 'Amanda McGarry',
      softwareDevelopment: 'Chris Malley (PixelZoom, Inc.)',
      team: 'Amy Hanson, Karina K. R. Hensberry, Ariel Paul, Kathy Perkins,\nSam Reid, Beth Stade, David Webb',
      qualityAssurance: 'Steele Dalton, Amanda Davis, Andrea Lin, Ben Roberts'
    }
```

@amanda-phet anything to change?

@phet-steele I'll check in with you on QA credits during RC test.

**Comment by amanda-phet** [comment]
Looks good to me

**Comment by pixelzoom** [comment]
@phet-steele please commit to master. i'll cherry pick to 1.0.

**Comment by phet-steele** [comment]
@pixelzoom commit made and referenced above.

**Comment by pixelzoom** [comment]
@phet-steele I added a line break to the QA credits, it was making the About dialog a bit wide. 

Here are the final credits:

![screenshot_32](https://cloud.githubusercontent.com/assets/3046552/26260016/e38e3a0a-3c88-11e7-84ea-87867b4e36c0.png)
