### ISSUE TITLE
Wrong See Inside image on the Mystery screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder-basics#15]
Shouldn't the See Inside checkbox on the Mystery screen use the same one as the Patterns screen (the one by the question mark in the below screenshot)? There are no numbers in this sim after all.

<img width="1700" alt="screen shot 2017-04-18 at 2 01 45 pm" src="https://cloud.githubusercontent.com/assets/5863899/25150748/3a845e68-2440-11e7-9886-fd1902f8edd5.png">

Seen on macOS 10.12.4 Chrome. For phetsims/tasks/issues/823.

URL: http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.3/function-builder-basics_en.html
Version: 1.0.0-dev.3 2017-04-18 15:39:14 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"00436448","branch":"master"},"babel":{"sha":"7840c860","branch":"master"},"brand":{"sha":"a4d6573f","branch":"master"},"chipper":{"sha":"628cdd7d","branch":"master"},"dot":{"sha":"f56a4411","branch":"master"},"function-builder":{"sha":"29939b75","branch":"master"},"function-builder-basics":{"sha":"c49121d8","branch":"master"},"joist":{"sha":"deef1bf3","branch":"master"},"kite":{"sha":"2d9c9d84","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"d0ffe176","branch":"master"},"query-string-machine":{"sha":"e7055778","branch":"master"},"scenery":{"sha":"69953c5c","branch":"master"},"scenery-phet":{"sha":"8707a265","branch":"master"},"sherpa":{"sha":"0e326d54","branch":"master"},"sun":{"sha":"cfea9c5a","branch":"master"},"tandem":{"sha":"30603e66","branch":"master"},"twixt":{"sha":"b1488b51","branch":"master"}}

**Comment by pixelzoom** [comment]
Indeed, that is incorrect.

**Comment by amanda-phet** [comment]
Yes, good point!

**Comment by pixelzoom** [comment]
Fixed in master https://github.com/phetsims/function-builder-basics/commit/817274b03997ae99102d129139dd22db9b61bd1f.  Screenshot below. @phet-steele please verify.

![screenshot_217](https://cloud.githubusercontent.com/assets/3046552/25151263/30d36a9c-2442-11e7-843a-0402d9c16ffd.png)

**Comment by phet-steele** [comment]
It's good! Thanks @pixelzoom.
