### ISSUE TITLE
Shorten the length of the mystery screen machines

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder-basics#16]
The Mystery screen in function-builder, from which function-builder-basics is adapted, has a 1, 2, and 3 slot machine. Each of the machines are long and of equal length. If I remember correctly, each machine was long to accommodate the two drawers needed. function-builder-basics doesn't have any drawers, but still has very long 1 and 2 slot machines (the 3 slot machine is of appropriate length). Are we free to shorten their length?

eg. This can be much shorter:
<img width="1577" alt="screen shot 2017-04-25 at 10 50 34 am" src="https://cloud.githubusercontent.com/assets/5863899/25397304/166d539e-29a5-11e7-8a16-b91b76ba9021.png">

1 slot length comparison on the Patterns screen:
<img width="1554" alt="screen shot 2017-04-25 at 10 51 54 am" src="https://cloud.githubusercontent.com/assets/5863899/25397358/37fadf4a-29a5-11e7-9248-966a0352a870.png">

2 slot length comparison from function-builder:
<img width="1574" alt="screen shot 2017-04-25 at 10 53 02 am" src="https://cloud.githubusercontent.com/assets/5863899/25397404/606f5dd4-29a5-11e7-8599-226b2583041e.png">

Seen on macOS 10.12.4 Chrome. For phetsims/tasks/issues/823.
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.3/function-builder-basics_en.html
Version: 1.0.0-dev.3 2017-04-18 15:39:14 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"00436448","branch":"master"},"babel":{"sha":"7840c860","branch":"master"},"brand":{"sha":"a4d6573f","branch":"master"},"chipper":{"sha":"628cdd7d","branch":"master"},"dot":{"sha":"f56a4411","branch":"master"},"function-builder":{"sha":"29939b75","branch":"master"},"function-builder-basics":{"sha":"c49121d8","branch":"master"},"joist":{"sha":"deef1bf3","branch":"master"},"kite":{"sha":"2d9c9d84","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"d0ffe176","branch":"master"},"query-string-machine":{"sha":"e7055778","branch":"master"},"scenery":{"sha":"69953c5c","branch":"master"},"scenery-phet":{"sha":"8707a265","branch":"master"},"sherpa":{"sha":"0e326d54","branch":"master"},"sun":{"sha":"cfea9c5a","branch":"master"},"tandem":{"sha":"30603e66","branch":"master"},"twixt":{"sha":"b1488b51","branch":"master"}}

**Comment by pixelzoom** [comment]
This seems like a good idea, so I went ahead and did it.  @amanda-phet please review - if you don't like it, it's easy to revert. 

Test drive here:
http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.4/function-builder-basics_en.html

Compare to previous version here:
http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.3/function-builder-basics_en.html

This change also motivated some cleanup in how "builder width" was handled across all of the screens (inconsistently, it turns out), so this work was worthwhile regardless.

**Comment by amanda-phet** [comment]
Looks great to me. Should we make the same change to the original Function Builder Mystery screen?

**Comment by pixelzoom** [comment]
No, we cannot make this change to the Function Builder "Mystery" screen.  As @phet-steele correctly stated above:
> If I remember correctly, each machine was long to accommodate the two drawers needed. 

E.g.:

![screenshot_231](https://cloud.githubusercontent.com/assets/3046552/25456315/c3d391a2-2a8f-11e7-8a8c-f589c1e597fe.png)

Closing.

**Comment by amanda-phet** [comment]
Oh right, of course, thanks. Looks great!
