### ISSUE TITLE
new patterns for Mystery screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#2]
From https://github.com/phetsims/function-builder/issues/103#issue-209883669:

@ariel-phet suggested adding additional input patterns to the revised Mystery screen. This should be as simple as adding new PNG files for the additional inputs. (See `PatternsScene.cardContent`.)

**Comment by pixelzoom** [comment]
Adding @ariel-phet as an assignee, since this was his idea.

**Comment by ariel-phet** [comment]
Here are a few ideas (not tied to any of them just some brain storming thoughts)

1. A single hand (in a similar style to the feet). I think it is nice to see that a "right hand" cannot be rotated into a "left hand" for instance.

2. Perhaps a flower with different color petals

3. Another stick figure in a different pose (something whimsical perhaps)

4. Something kids would find fun/exciting....a simple dinosaur or such?

5. Something sort of "wildly" colorful (maybe the flower could achieve this thought)

6. I wonder if a "perspective cube" would be interesting

7. Perhaps a famous/recognizable symbol? The yin-yang, the Olympic rings, the recycling symbol

8. A popular emoji?

9. A heart shape?

**Comment by pixelzoom** [comment]
10. A PhET paper airplane? 

11. PHET girl, or one of the PhET people from another sim?

**Comment by amanda-phet** [comment]
If we go this route, why only include them on the mystery screen? It seems like these would be beneficial to have in the exploration screen (especially given the reasoning for the right hand). Or are you suggesting that these *replace* the inputs, so that on the mystery screen they can't rely on their memory as much?

**Comment by pixelzoom** [comment]
Not suggesting that we replace anything.  It would be fine to also add them to the Patterns screen.  I just thought it would fun if they encountered something new on the Mystery screen.

**Comment by pixelzoom** [comment]
And we may want to play around with the existing patterns on the Mystery screen before deciding whether to add more.  We may already have enough.

**Comment by pixelzoom** [comment]
@amanda-phet @ariel-phet Decision time!  Do we need more input cards? If so, what are they?

Please play with this dev version to form your decision: 
http://www.colorado.edu/physics/phet/dev/html/function-basics/1.0.0-dev.1/function-basics_en.html

**Comment by pixelzoom** [comment]
I should also mention... If we decide to add new input cards to the Patterns screen, we should be prepared to do so for both Function Builder and Function Basics.  Other than background color, there is currently no customization available for the Patterns screen; it is used "as is" in both sims.

**Comment by pixelzoom** [comment]
... and unless we're willing to live with blank spaces in the input carousel, the total number of input cards needs to be a multiple of 4.  So we'd need to add a minimum of 4 new inputs.

**Comment by ariel-phet** [comment]
Since the patterns screen is so popular (especially with younger kids) I would be a fan of adding 4 more patterns that are a little more on the "whimsy" side

**Comment by pixelzoom** [comment]
4/13/17 design meeting:  @amanda-phet will decide whether to add 4 more inputs, and which screen(s) to add them to.

Note that if add more inputs to the Patterns screen, they will also appear in Function Builder, and will require a full test/publish cycle for that sim.

**Comment by amanda-phet** [comment]
I see some value in having *new* inputs that are more "fun", but I don't agree with the value in having *additional* inputs. In fact, in an informal "interview" with a 5th grade student today, she did swipe through each carousel and dragged all 12 inputs through the builder, but she did it so fast that I don't think an extra four would have improved her experience with the sim. There is SO much to play with on that screen with all of the function combinations, and I think figuring out the functions is where students will continue to spend their time. So, I am deciding to keep the inputs as they are.
