### ISSUE TITLE
finalize the name for this sim and its repository

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#4]
"Function Basics" and function-basics are the names that we went with in https://github.com/phetsims/function-builder/issues/103#issuecomment-284834493. 

"Function Basics" is inconsistent with other uses of "Basics" - it has no colon separator. E.g. "Energy Skate Park: Basics", "Forces and Motion: Basics".  I found no other cases where the ": Basics" convention isn't followed, so "Function Basics" would be the first to break it.  I don't know how important the ": Basics" branding is to PhET, just pointing it out.

Other possibilities from https://github.com/phetsims/function-builder/issues/103:
> Function Builder: Patterns
Pattern Builder
Pattern Functions

**Comment by pixelzoom** [comment]
I suspect that the name of this sim may change.  So I'm used placeholder `SIM_NAME` in the code. When the name is finalized, globally replace `SIM_NAME`.

**Comment by amanda-phet** [comment]
@ariel-phet can we call it Function Builder: Basics? Or does this sim break with the "Basics" convention used in other sims because of the Mystery screen?

**Comment by pixelzoom** [comment]
I'm happy to report that this sim progressed _way_ faster than anticipated. It is now feature complete, and should wrap up quickly.  So - time to commit to a name.

**Comment by ariel-phet** [comment]
@amanda-phet we certain can go with Function Builder: Basics (there are no "hard and fast" rules as to what we term Basics). My only concern is that name is fairly verbose, but this sim is clearly a subset. I think we will also want to change the Function Builder main screenshot to be more "mathematical" (graphs/numbers) and do the pattern screen for this sim.

**Comment by pixelzoom** [comment]
Function Basics seems awfully general, and I think the "builder" aspect is the core of these sims.

I like either "Function Builder: Basics" or "Function Builder: Patterns" (with a slight preference for the latter). 

Related issue... Function Basics is also problematic because we typically use initials ("FB") as a suffix to prevent files from having identical names.  Since Function Basics and Function Builder have the same initials, I haven't been able to do that.  So I have a collection of files (for the Mystery screen) which have identical names for the 2 sims - quite confusing.

**Comment by amanda-phet** [comment]
Decision at 4/13/17 design meeting: 

Function Builder: Basics

**Comment by pixelzoom** [comment]
I renamed the repository, renamed .js files that must correspond to the repository name, and add 'FBB' prefix to mystery package files (to distinguish them from similar files in function-builder).

The function-basics/ directory on spot@dev/html is orphaned and will be left in place.

Closing.
