### ISSUE TITLE
how to generate Mystery challenges?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#7]
Related to the revised Mystery screen (https://github.com/phetsims/function-basics/issues/5)...

The Mystery screen in Function Builder had a "pool" of challenges for each level, from which challenges were randomly selected.   See [MysteryChallenges.js](https://github.com/phetsims/function-builder/blob/master/js/mystery/model/MysteryChallenges.js). 

For the pattern-based Mystery screen, how do you want to handle challenge generation?  Can we just randomly select functions?  Are duplicates allowed?  Does it depend on the function? (e.g. probably don't want more than 1 Erase function.)

@amanda-phet let's flesh this out together in this issue. @ariel-phet feel free to chime in.

**Comment by pixelzoom** [comment]
Note that in [MysteryChallenges.js](https://github.com/phetsims/function-builder/blob/master/js/mystery/model/MysteryChallenges.js), the first challenge in each "pool" is documented like this:

```js
    // 1-function challenges
    POOL1: [
      '+ 3', // selected on startup and reset
      ...

    // 2-function challenges
    POOL2: [
      '+ 1 * 2', // selected on startup and reset
      ...

    // 3-function challenges
    POOL3: [
      '+ 2 * 1 + 2', // selected on startup and reset
      ...
```

This first challenge is selected on startup, and restored on reset.  I seem to recall that this was done so that teachers had a known challenge that they could start with (and return to). 

Do we want to do something similar for pattern functions?

**Comment by ariel-phet** [comment]
I would think we would want a similar behavior in terms of having a known challenge that can be returned to when pressing reset.

As for challenges, I think allowing duplicates would be fine. I am not sure if I would worry about a duplicate erase, I do not necessarily think that causes an issue. For instance if I had "Erase-Erase-Shrink" I could probably make a guess that I had "Something-Something-Erase" and just thought the last function was Erase. There is a nice discovery (I hope) when students see that different guesses could work in certain cases.

Deferred to @amanda-phet for final decisions, but those are my thoughts

**Comment by amanda-phet** [comment]
Yes @pixelzoom I'd like to keep the same structure for this sim. 

I can begin working on the sets of challenges to choose from.. I'd like to keep pools to choose from because they were very intentional challenges we selected. For example, we allowed some like +3 •1 •1 even though it can be represented with just +3, but we also wanted to limit that type of challenge.

**Comment by pixelzoom** [comment]
In Function Builder, the "Patterns" screen has 3 mystery functions:

![screenshot_199](https://cloud.githubusercontent.com/assets/3046552/24813883/f3e39c0a-1b8c-11e7-8006-daa03a3c44f8.png)

For the game in Function Basics, do you want to (a) omit these functions, or (b) create icons for these functions that depict what they do?  (a) would certainly be easier, and would leave us with 9 pattern functions.

@amanda-phet @ariel-phet your opinion?

**Comment by pixelzoom** [comment]
I'm noticing a potential problem for 2 and 3 function challenges.  

Excluding the A, B and C mystery functions, We have this set of pattern functions:

Erase
Grayscale
Identity
InvertRGB
Mirror
Rotate90
Rotate180
Shrink
Warhol

For many of the 2 and 3 function challenges, the result is the same regardless of the order of the above functions.  For example:

`Rotate90 -> Grayscale` is the same as `Grayscale -> Rotate`
`Warhol -> Shrink` is the same as `Shrink -> Warhol`
`Rotate90 -> Mirror -> Grayscale` is the same as `Grayscale -> Mirror -> Rotate90`
etc.

The only combinations I've found that are _not_ the same are challenges that consist exclusively of `Warhol`, `Grayscale`, and `InvertRGB`.

This would seem like a significant impediment to guess the identity of 2- and 3-function challenges. 

@amanda-phet your thoughts?

**Comment by pixelzoom** [comment]
How to generate challenges seems to be resolved - we'll use predefined pools, as we did in Function Builder. 

Now we need to specify the challenge pools. We'll do that in issue #11.

Closing.
