### ISSUE TITLE
new icon for Mystery screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#8]
Since the look of hidden functions is likely to change (see #1), we will likely need a new icon for the Mystery screen.

**Comment by pixelzoom** [comment]
I made the Mystery screen icon look similar to the look of the hidden functions (see #1).  The background color may change (see #12).  Here's what it currently looks like in [1.0.0-dev.1](http://www.colorado.edu/physics/phet/dev/html/function-basics/1.0.0-dev.1/function-basics_en.html).

![screenshot_212](https://cloud.githubusercontent.com/assets/3046552/24985380/eb51fafa-1fb0-11e7-8dc6-bcc249898b8f.png)

**Comment by pixelzoom** [comment]
@amanda-phet @ariel-phet feedback?

**Comment by ariel-phet** [comment]
That generally looks good to me. I think we may do some minor tweaking to the question mark, but I like the idea of using the "mystery" card as the icon.

**Comment by pixelzoom** [comment]
Looks good, used `weight: bold` for question mark.  Need to do this in Function Builder too.

**Comment by pixelzoom** [comment]
Done, closing.
